#!/usr/local/bin/python3

import random

MAX_BOGUS_TRIES = 5

def get_answer():
    tries = 0
    while(1):
        try:
            ans = int(input())
            return ans
        except:
            print("please answer with a number only (no alpha / punctuation)")
            tries +=1
            if(tries >= MAX_BOGUS_TRIES):
                print("Clearly you're not paying attention. Good bye!")
                exit(0)

def game_over():
    CONTINUE_RESPONSES = ["", "Y", "y"]
    GAME_OVER_RESPONSES = ["n", "N"]
    tries = 0
    while(1):  
        print("continue? ([Y]/n)")
        ans = input()
        if ans in CONTINUE_RESPONSES:
            return False
        elif ans in GAME_OVER_RESPONSES:
            return True
        else:
            print("please answer with a number only (no alpha / punctuation)")
            tries += 1
            if(tries >= MAX_BOGUS_TRIES):
                print("Clearly you're not paying attention. Game Over!")
                return True

def game():
    correct = 0
    correct_ans = set()
    incorrect = 0
    incorrect_ans = set()
    while(1):
        exponent = random.randint(0, 16)
        question = "2^%d" % (exponent)
        print("what's %s?" % question)
        ans = get_answer()
        actual = 2**exponent
        eq = "%s = %d"%(question,actual)
        if(ans == actual):
            print("Correct!")
            correct+=1
            correct_ans.add(eq)
        else:
            print("Incorrect: 2^%d = %d" % (exponent, actual))
            incorrect += 1
            incorrect_ans.add(eq)
        if game_over():
            return "Results: \nTotal Questions: %d\nCorrect: %d -> %s\nIncorrect: %d -> %s"%(correct+incorrect, correct, correct_ans, incorrect, incorrect_ans)

def main():
    print("TWOS REVIEW:")
    print("Time to review the powers of TWO!")
    results = game()
    print(results)
    print("GAME OVER")


if __name__ == "__main__":
    main()
